AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repository for Node.js application

Parameters:
  RepositoryName:
    Type: String
    Default: node-app

Resources:
  AppECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      EncryptionConfiguration:
        EncryptionType: AES256

Outputs:
  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt AppECRRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepositoryUri"
