FROM ubuntu:22.04

RUN apt update && apt install -y openjdk-17-jre-headless

RUN mkdir -p /opt/app

ENV PROJECT_HOME /opt/app

COPY spring-boot-mongo.jar $PROJECT_HOME/spring-boot-mongo.jar

WORKDIR $PROJECT_HOME

EXPOSE 8080

CMD ["java", "-Dspring.data.mongodb.uri=mongodb://mongo:27017/spring-mongo", "-Djava.security.egd=file:/dev/./urandom", "-jar", "./spring-boot-mongo.jar"]
